version: 2

jobs:
  test-crystal: &test-template
    docker:
      - image: crystallang/crystal:0.27.0
    steps:
      - checkout
      - run: shards
      - run: ./bin/static-analysis
      - run: ./bin/code-style
      - run: SPEC_VERBOSE=1 ./bin/test
      - run: SPEC_VERBOSE=1 ./bin/test-coverage
  test-crystal-0.27.0:
    <<: *test-template
    docker:
      - image: crystallang/crystal:0.27.0
  test-mutations:
    docker:
      - image: crystallang/crystal:0.27.0
    steps:
      - checkout
      - run: shards
      - run: make bin
      - run: ./bin/test-mutations

workflows:
  version: 2
  ci:
    jobs:
      - test-crystal-0.27.0
      - test-mutations
